language: python
cache: pip
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

before_install:
  - sudo bash bin/deploy/install_system_dependencies.sh

install:
  - bash bin/deploy/install_python_dependencies.sh

script:
  - sudo bash run_tests.sh

after_success:
    - sudo bash bin/deploy/merge_develop_to_master.sh

before_deploy:
  - echo "Deployment preperation"
  - sudo bash setup.sh
  - bash bin/deploy/new_release_auto_tagging.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: jarvis_package.tar
  on:
    branch: master

notifications:
  email: false
