language: python
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

install:
  - sudo bash setup.sh
script:
  - sudo bash run_tests.sh
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master