language: python
matrix:
  include:
    - name: "Ubuntu 20.04 Job"
    - python:
        - "3.8"
    - os: linux
    - dist: focal

install:
  - sudo bash setup.sh
script:
  - sudo bash run_tests.sh
notifications:
  email: false
