dist: bionic # Run build in Ubuntu 18.04 platform
language: python
python:
  - "3.5"
  - "3.6"
install:
  - sudo bash setup.sh
  - cd src/jarvis
script:
  - nosetests -v --with-coverage ../tests
notifications:
  email: false
