language: python
matrix:
  include:
    - name: "Ubuntu 20.04 Job"
    - os: linux
    - dist: focal
    - python:
        - "3.8"

install:
  - sudo bash setup.sh
script:
  - sudo bash run_tests.sh
notifications:
  email: false
