language: python
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

install:
  - echo "sudo bash setup.sh"
  on:
    branch: develop

script:
  - echo "sudo bash run_tests.sh"
  on:
    branch: develop

notifications:
  email: false

after_success:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-branches --add origin master || echo "Set origin master failed"
    - git fetch
    - git reset --hard
    - git checkout master || echo "Git checkout master failed"
    - git merge "$TRAVIS_COMMIT" || echo "Merge develop to master failed"
    - git push -q https://$GITHUB_TOKEN@github.com/ggeop/Python-ai-assistant master
  on:
    branch: develop

before_deploy:
  - echo "Build Jarvis package"
  - tar -cvf jarvis_package.tar -T config/package_file_list.txt
  - echo "Add tags to new release"
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_TOKEN@github.com/ggeop/Python-ai-assistant --tags
  on:
    branch: master

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: jarvis_package.tar
  on:
    branch: master