language: python
cache: pip

os: linux
dist: focal
python: 3.8

jobs:
  include:
    - stage: test
      before_install:
        - sudo bash bin/deploy/install_system_dependencies.sh
      install:
        - bash bin/deploy/install_python_dependencies.sh
      script:
        - sudo bash bin/tests/run_tests_on_travis.sh
    - stage: merge (feature branch --> develop)
      install: skip
      script:
        - sudo bash bin/deploy/merge_feature_branch_to_develop.sh
    - stage: merge (develop --> master)
      install: skip
      script:
        - bash bin/deploy/new_release_auto_tagging.sh
        - sudo bash bin/deploy/merge_develop_to_master.sh
    - stage: deploy
      install: skip
      script: skip
      env:
        - RELEASE_PACKAGE=jarvis_package.tar
      before_deploy:
        - sudo bash setup.sh
        - sudo bash run_tests.sh
        - bash bin/deploy/create_release_package.sh
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: $RELEASE_PACKAGE

stages:
  - name: test
    if: NOT(branch==master)
  - name: merge (feature branch --> develop)
    if: (NOT (branch IN (develop,master))) AND (NOT(type==pull_request))
  - name: merge (develop --> master)
    if: branch==develop AND (NOT(type==pull_request))
  - name: deploy
    if: branch==master AND (NOT(type==pull_request))

notifications:
  email: false