language: python
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

before_install:
- sudo apt-get update
- sudo apt-get install build-essential
- sudo apt-get install python3-dev
- sudo apt-get install python3-setuptools
- sudo apt-get install python3-pip
- sudo apt-get install python3-venv
- sudo apt-get install portaudio19-dev python3-pyaudio python3-pyaudio
- sudo apt-get install libasound2-plugins libsox-fmt-all libsox-dev libxml2-dev libxslt-dev sox ffmpeg
- sudo apt-get install espeak
- sudo apt-get install libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0
- sudo apt install mongodb
- sudo apt-get install gnupg


install:
  - echo "Install"
  - pip install -r requirements.txt
  - pip install -U scikit-learn

script:
  - sudo bash run_tests.sh

#notifications:
#  email: false
#
#after_success:
#  - sudo bash ./Scripts/merge_develop_to_master.sh
#
#before_deploy:
#  - echo "Build Jarvis package"
#  - tar -cvf jarvis_package.tar -T config/package_file_list.txt
#  - echo "Add tags to new release"
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - git push -q https://$GITHUB_TOKEN@github.com/ggeop/Python-ai-assistant --tags
#
#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key: $GITHUB_TOKEN
#  file: jarvis_package.tar
#  on:
#    branch: master