language: python
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

install:
  - echo 1
script:
  - echo 2
notifications:
  email: false

before_deploy:
  - echo "Build Jarvis package"
  - tar -cvf jarvis_package.tar -T package_file_list.txt

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: jarvis_package.tar
  on:
    branch: master