language: python
cache: pip
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

before_install:
  - bin/deploy/install_system_dependencies.sh

install:
  - bin/deploy/install_python_dependencies.sh

script:
  - sudo bash run_tests.sh

#notifications:
#  email: false
#
#after_success:
#  - sudo bash ./Scripts/merge_develop_to_master.sh
#
#before_deploy:
#  - echo "Build Jarvis package"
#  - tar -cvf jarvis_package.tar -T config/package_file_list.txt
#  - echo "Add tags to new release"
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - git push -q https://$GITHUB_TOKEN@github.com/ggeop/Python-ai-assistant --tags
#
#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key: $GITHUB_TOKEN
#  file: jarvis_package.tar
#  on:
#    branch: master