language: python
cache: pip

os: linux
dist: focal
python: 3.8

env:
  - RELEASE_PACKAGE=jarvis_package.tar

jobs:
  include:
    - stage: test
      script:
        - sudo bash bin/deploy/install_system_dependencies.sh
        - bash bin/deploy/install_python_dependencies.sh
        - sudo bash bin/tests/run_tests_on_travis.sh
      after_success:
        - sudo bash bin/deploy/merge_develop_to_master.sh
    - stage: deploy
      before_deploy:
        - sudo bash setup.sh
        - sudo bash run_tests.sh
        - bash bin/deploy/new_release_auto_tagging.sh
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: $RELEASE_PACKAGE
        on:
          branch: master

notifications:
  email: false