language: python
jobs:
  include:
    - name: "Python 3.8 on Focal"
      os: linux
      dist: focal
      python: 3.8

install:
  - echo 1
script:
  - echo 2
notifications:
  email: false

before_deploy:
  - echo "Build Jarvis package"
  - tar -cvf jarvis_package.tar -T config/package_file_list.txt
  - echo "Add tags to new release"
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push git push origin --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: jarvis_package.tar
  on:
    branch: master